---
# tasks file for setup-user-home
#

# setup test dev users 
# all intermediate subdirectories will be created if they do not exist
- name: "create home dir for sample test dev users"
  file:
    path: "/home/userdev{{ item }}/.ssh"
    owner: userdev{{ item }}
    group: testdevs
    mode: '0700'
    state: directory
  loop: "{{ range(1,11,1) | list }}"
  tags:
    - create-testdev-home-dirs

- name: "create ssh priv/pub keys for sample test dev users"
  openssh_keypair:
    path: "/home/userdev{{ item }}/.ssh/id_ed25519"
    owner: userdev{{ item }}
    group: testdevs
    mode: '0600' 
    type: ed25519
    comment: userdev{{ item }}
  loop: "{{ range(1,11,1) | list }}"
  tags:
    - create-testdev-ssh-keys

- name: "create simulated totp files"
  copy:
    dest: "/home/userdev{{ item }}/.ssh/totp"
    content: "userdev{{ item }}"
    owner: userdev{{ item }}
    group: testdevs
    mode: '0600'
  loop: "{{ range(1,11,1) | list }}"
  when: inventory_hostname in groups['dummy_totp']
  tags:
    - create-testdev-totp
    

