---
# tasks file for totp

- debug: msg="{{ ansible_distribution_major_version }}"

- name: "selinux in permissive mode"
  selinux:
    policy: targeted
    state: permissive
  tags:
    - disable-selinux

- name: "setenforce permissive selinux"
  command: /usr/sbin/setenforce 0
  when:
    - ansible_selinux.mode == 'enforcing'
  tags:
    - disable-selinux

- debug: msg="{{ epel_repo_gpg_key_url }}"

# import via EPEL URL
- name: "Import EPEL GPG key"
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  register: import_result
  until: import_result is succeeded
  retries: 5
  delay: 10
  tags:
    - install-google-auth

# install via EPEL URL
- name: "Install google-authenticator"
  dnf: 
    name: "{{ google_authenticator_rpm }}"
    state: present
  register: install_result
  until: install_result is succeeded
  retries: 5
  delay: 10
  tags:
    - install-google-auth

- name: "Install qrencode packages"
  dnf:
    name: "{{ qrencode_packages }}"
    state: present
  tags:
    - install-google-auth

- name: "Create test users"
  user:
    name: "{{ item }}"
    comment: "{{ item }}"
    shell: "/bin/bash"
  loop: "{{ local_users }}"
  tags:
    - create-test-users

- name: "Copy public key to test user"
  authorized_key:
    user: "{{ item }}"
    key: "{{ testdev_pk }}"
  loop: "{{ local_users }}"
  tags:
    - copy-ssh-keys
    - copy-public-key

- name: "Copy test private key to test user"
  copy:
    src: id_ed25519_test
    dest: "/home/{{ local_users | first }}/.ssh/id_ed25519_test"
    owner: "{{ local_users | first }}"
    group: "{{ local_users | first }}"
    mode: '0600'
  tags:
    - copy-ssh-keys
    - copy-private-key

- name: "Deploy updated /etc/pam.d/sshd"
  template:
    src: pam.d/sshd.j2
    dest: /etc/pam.d/sshd
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
    - restart sshd
  tags:
    - deploy-pam-sshd
    - deploy-ssh-configs

- name: "Deploy updated /etc/ssh/sshd_config"
  template:
    src: ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    backup: yes
  notify:
    - restart sshd
  tags:
    - deploy-sshd-config
    - deploy-ssh-configs

- name: "copy test9 totp"
  copy:
    src: totp.test9
    dest: /home/test9/.ssh/totp
    owner: test9
    group: test9
    mode: '0400'
  when: 
    - copy_totp | bool
  tags: 
    - copy-totp

# google-authenticator --secret=/home/$USER/.ssh/totp --time-based --disallow-reuse --rate-limit=3 --rate-time=30 --window-size=3 --step-size=30 --qr-mode=UTF8 --force 
