---

- name: "distribute totp content per user and netgroup"
  copy:
    content: "{{ item.content | b64decode | trim }}"
    dest: /home/{{ item.item.pw_name }}/.ssh/totp
    owner: "{{ item.item.pw_name }}"
    mode: '0600'
  with_items: "{{ hostvars.testdev2.totpfiles_content }}"
  when:
    - inventory_hostname in groups[outside_dist_item.host]
    - "'{{ item.item.pw_name }}' == '{{ outside_dist_item.uid }}'"
  tags:
    - distribute-totp-files


