---
 
- name: "distribute totp content per user and netgroup"
  copy:
    content: "{{ item.content | b64decode | trim }}"
    dest: /home/{{ item.item.pw_name }}/.ssh/totp
    owner: "{{ item.item.pw_name }}"
    mode: '0600'
  with_items:
    - "{{ hostvars.testdev2.totp_content }}"
    # - "{{ hostvars.testdev2.totpfiles_content.results }}"
  when:
    - host_netgroup_list is subset group_names
    - item.item.pw_name in uid_list
    #- outside_dist_item.host is subset group_names
    #- inventory_hostname in groups[outside_dist_item.host]
  vars:
    uid_list: "{{ outside_dist_item.uid | trim | split }}"
    host_netgroup_list: "{% if outside_dist_item.host is string %}{{ outside_dist_item.host | trim | split }}{% else %}{{ outside_dist_item.host }}{% endif %}"
    #host_netgroup_list: "{{ outside_dist_item.host if (outside_dist_item.host is iterable) else (outside_dist_item.host | trim | split) }}"
  tags:
    - distribute-totp-files

#- debug: var=group_names
#- debug: var=groups
