---
# tasks file for dist-totp-data

- name: "debug totpfiles_content"
  debug:
    msg: "{{ hostvars.testdev2.totp_content }}"

- name: "debug ldap_uid_and_host_content"
  debug:
    msg: "{{ hostvars.testdev2.ldap_uid_and_host_content }}"

- import_tasks: init.yml
- import_tasks: distribute-totp-files.yml
