---

- name: "find totp files"
  find:
    paths: /home
    patterns: "^totp$"
    use_regex: yes
    file_type: file
    recurse: yes
    excludes: "mysql,nginx"
  register: totpfiles_found
  when: inventory_hostname in groups['sssd_client']
  tags:
    - distribute-totp-files

- name: "debug totpfiles_found"
  debug:
    msg: "{{ item }}"
  loop: "{{ totpfiles_found.files }}"
  when: inventory_hostname in groups['sssd_client']
  tags:
    - distribute-totp-files
