---
# tasks file for deploy-auth-data
#

- name: "debug sshpk_content"
  debug:
    msg: "{{ hostvars.testdev2.sshpk_content }}"

- import_tasks: init.yml
- import_tasks: update-ldap-slurp.yml
- import_tasks: distribute-totp-files.yml

