---

- name: "get ldap uid and host attrs"
  community.general.ldap_search:
    dn: "ou=People,{{ ldap_search_base }}"
    scope: "onelevel"
    attrs:
      - "uid"
      - "host"
  register: ldap_uid_and_host
  tags:
    - get-uid-and-host

- name: "debug register ldap_uid_and_host"
  debug:
    var: ldap_uid_and_host.results
  tags:
    - get-uid-and-host

- name: "get netgroup info"
  community.general.ldap_search:
    dn: "cn={{ item.host }},ou=Netgroup,{{ ldap_search_base }}"
    scope: "onelevel"
    attrs:
      - "cn"
      - "nisNetgroupTriple"
  loop: "{{ ldap_uid_and_host.results }}"
  register: ldap_uid_and_netgroup_hosts
  when: item.host is defined
  tags:
    - get-uid-and-host

- name: "debug register ldap_uid_and_netgroup_hosts"
  debug:
    var: ldap_uid_and_netgroup_hosts.results
  tags:
    - get-uid-and-host
