---

- name: "install openldap-clients software"
  dnf:
    name: [ 'openldap-clients', 'python3-ldap' ]
    state: present


# ldap_entry can't get used to update an existing ldap entry
# can only be used to initially create ldap entry
#
- name: "add user public keys to ldap"
  ldap_attrs:
    dn: "uid={{ item.item.pw_name }},ou=People,{{ ldap_search_base }}"
    attributes:
      sshPublicKey: "{{ item.content | b64decode | trim }}"
    bind_dn: "{{ ldap_auth.bind_dn }}"
    bind_pw: "{{ ldap_auth.bind_pw }}"
  loop: "{{ hostvars.testdev2.sshpk_content }}"
  tags:
    - add-publickey-ldap

