---

- name: "find fetched ssh public key files"
  find:
    paths: "{{ fetch_pk_dir }}"
    patterns: "^id_.*pub$"
    use_regex: yes
    file_type: file
    recurse: yes
    excludes: "mysql,nginx"
  register: sshpubkeys_found
  delegate_to: localhost
  become: no
  tags:
    - add-publickey-ldap
    - check-local-pubkeys

- name: "debug sshpubkeys_found" 
  debug:
    msg: "{{ item.path | split('/') }} "
  loop: "{{ sshpubkeys_found.files }}"
  register: sshpubkeys_split
  when: debug_me | bool
  tags:
    - check-local-pubkeys

- name: "add user public keys to ldap"
  ldap_attrs:
    dn: "uid={{ [lookup('ansible.utils.index_of', item.path | split('/') , 'eq', '.ssh', wantlist=False) - 1] | map( 'extract', (item.path | dirname | split('/')) ) | join }},ou=People,{{ ldap_search_base }}"
    attributes:
      sshPublicKey: "{{ lookup('file', '{{ item.path }}') }}"
    server_uri: "ldaps://{{ ldap_uri_host }}"
    bind_dn: "{{ ldap_auth.bind_dn }}"
    bind_pw: "{{ ldap_auth.bind_pw }}"
    validate_certs: false
  loop: "{{ sshpubkeys_found.files }}"
  tags:
    - add-publickey-ldap

- name: "remove fetched public keys"
  file:
    path: "{{ fetch_pk_dir }}"
    state: absent
  connection: local
  become: no
  tags:
    - add-publickey-ldap


